name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@37c2f74d0dbeb6be81024420734dcec9790e9a5c # main
    secrets: inherit
