name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@6e7ff3d2cef36255edda0d51caf1a5428687ec4f # main
    secrets: inherit
