name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build_validate_test:
    uses: openmcp-project/build/.github/workflows/ci.lib.yaml@3051802a4f3fc6b250d6374b196075cec8390bf7 # main
    secrets: inherit
