name: E2E Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-e2e:
    name: E2E Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: task generate
        run: |
          task generate --verbose

      - name: task validate
        run: task validate --verbose

      - name: Running Test e2e
        run: task test-e2e
