name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@0853da91ab09626a07d3495f3d31bed3ede22ed5 # main
    secrets: inherit