name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
    uses: openmcp-project/build/.github/workflows/publish.lib.yaml@37c2f74d0dbeb6be81024420734dcec9790e9a5c # main
    secrets: inherit
