name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@087dc370eb85bfda59bf138fec8e36c97fce5933 # main
    secrets: inherit
