name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@37c2f74d0dbeb6be81024420734dcec9790e9a5c # main
    secrets: inherit
