name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@b3bfce9507f77f6f62c769634cb8da1da64177a1 # main
    secrets: inherit
