name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@58c5ff00ec953dd6b5908f6658f1d1b522c06431 # main
    secrets: inherit
